//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace th.AdminibotLegacy.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("th.AdminibotLegacy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Admin {
            get {
                object obj = ResourceManager.GetObject("Admin", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap avatar_hugo64 {
            get {
                object obj = ResourceManager.GetObject("avatar_hugo64", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap avatar_timo64 {
            get {
                object obj = ResourceManager.GetObject("avatar_timo64", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Broadcaster {
            get {
                object obj = ResourceManager.GetObject("Broadcaster", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; already exists. (@{1}).
        /// </summary>
        internal static string CommandAddcomExists {
            get {
                return ResourceManager.GetString("CommandAddcomExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; has been created. (@{1}).
        /// </summary>
        internal static string CommandAddcomSuccess {
            get {
                return ResourceManager.GetString("CommandAddcomSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a battletag. (@{0}).
        /// </summary>
        internal static string CommandBtagMainNotFound {
            get {
                return ResourceManager.GetString("CommandBtagMainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your battletag is &quot;{0}&quot;. (@{1}).
        /// </summary>
        internal static string CommandBtagMainSuccess {
            get {
                return ResourceManager.GetString("CommandBtagMainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; hasn&apos;t set a battletag. (@{1}).
        /// </summary>
        internal static string CommandBtagRemoveModNoTag {
            get {
                return ResourceManager.GetString("CommandBtagRemoveModNoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandBtagRemoveModNotFound {
            get {
                return ResourceManager.GetString("CommandBtagRemoveModNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s battletag was cleared. (@{1}).
        /// </summary>
        internal static string CommandBtagRemoveModSuccess {
            get {
                return ResourceManager.GetString("CommandBtagRemoveModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t set a battletag. (@{0}).
        /// </summary>
        internal static string CommandBtagRemoveNoTag {
            get {
                return ResourceManager.GetString("CommandBtagRemoveNoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your battletag was cleared. (@{0}).
        /// </summary>
        internal static string CommandBtagRemoveSuccess {
            get {
                return ResourceManager.GetString("CommandBtagRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandBtagSetModNotFound {
            get {
                return ResourceManager.GetString("CommandBtagSetModNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s battletag was set to &quot;{1}&quot;. (@{2}).
        /// </summary>
        internal static string CommandBtagSetModSuccess {
            get {
                return ResourceManager.GetString("CommandBtagSetModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battletags can&apos;t be longer than {0} characters. (@{1}).
        /// </summary>
        internal static string CommandBtagSetModTooLong {
            get {
                return ResourceManager.GetString("CommandBtagSetModTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your battletag was set to &quot;{0}&quot;. (@{1}).
        /// </summary>
        internal static string CommandBtagSetSuccess {
            get {
                return ResourceManager.GetString("CommandBtagSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battletags can&apos;t be longer than {0} characters. (@{1}).
        /// </summary>
        internal static string CommandBtagSetTooLong {
            get {
                return ResourceManager.GetString("CommandBtagSetTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandDelcomNotFound {
            get {
                return ResourceManager.GetString("CommandDelcomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; has been removed. (@{1}).
        /// </summary>
        internal static string CommandDelcomSuccess {
            get {
                return ResourceManager.GetString("CommandDelcomSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandEditcomNotFound {
            get {
                return ResourceManager.GetString("CommandEditcomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;!{0}&quot; has been updated. (@{1}).
        /// </summary>
        internal static string CommandEditcomSuccess {
            get {
                return ResourceManager.GetString("CommandEditcomSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The commands for {0}s are: {1}. (@{2}).
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of &quot;{0}&quot;: {1} - {2} (@{3}).
        /// </summary>
        internal static string CommandHelpCommand {
            get {
                return ResourceManager.GetString("CommandHelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The commands for &quot;{0}&apos; are: {1}. (@{2}).
        /// </summary>
        internal static string CommandHelpGroup {
            get {
                return ResourceManager.GetString("CommandHelpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody received {0} points from {1}..
        /// </summary>
        internal static string CommandPointsAddAllSuccess {
            get {
                return ResourceManager.GetString("CommandPointsAddAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandPointsAddNotFound {
            get {
                return ResourceManager.GetString("CommandPointsAddNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All online users received {0} points from {1}..
        /// </summary>
        internal static string CommandPointsAddOnlineSuccess {
            get {
                return ResourceManager.GetString("CommandPointsAddOnlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} received {1} points from {2}..
        /// </summary>
        internal static string CommandPointsAddSuccess {
            get {
                return ResourceManager.GetString("CommandPointsAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody&apos;s points were cleared by {0}..
        /// </summary>
        internal static string CommandPointsClearAllSuccess {
            get {
                return ResourceManager.GetString("CommandPointsClearAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandPointsClearNotFound {
            get {
                return ResourceManager.GetString("CommandPointsClearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All online user&apos;s points were cleared by {0}..
        /// </summary>
        internal static string CommandPointsClearOnlineSuccess {
            get {
                return ResourceManager.GetString("CommandPointsClearOnlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s points were cleared by {1}..
        /// </summary>
        internal static string CommandPointsClearSuccess {
            get {
                return ResourceManager.GetString("CommandPointsClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;!point&quot; commands have been disabled. (@{0}).
        /// </summary>
        internal static string CommandPointsEnabledOffSuccess {
            get {
                return ResourceManager.GetString("CommandPointsEnabledOffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;!point&quot; commands have been enabled. (@{0}).
        /// </summary>
        internal static string CommandPointsEnabledOnSuccess {
            get {
                return ResourceManager.GetString("CommandPointsEnabledOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandPointsGetNotFound {
            get {
                return ResourceManager.GetString("CommandPointsGetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} currently has {1} points. (@{2}).
        /// </summary>
        internal static string CommandPointsGetSuccess {
            get {
                return ResourceManager.GetString("CommandPointsGetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have {0} points. (@{1}).
        /// </summary>
        internal static string CommandPointsMainSuccess {
            get {
                return ResourceManager.GetString("CommandPointsMainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t exist in the database yet. Please try again. (@{0}).
        /// </summary>
        internal static string CommandPointsMainWait {
            get {
                return ResourceManager.GetString("CommandPointsMainWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} took {1} points from everybody..
        /// </summary>
        internal static string CommandPointsRemoveAllSuccess {
            get {
                return ResourceManager.GetString("CommandPointsRemoveAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandPointsRemoveNotFound {
            get {
                return ResourceManager.GetString("CommandPointsRemoveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} took {1} points from all online users..
        /// </summary>
        internal static string CommandPointsRemoveOnlineSuccess {
            get {
                return ResourceManager.GetString("CommandPointsRemoveOnlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} took {1} points from {2}..
        /// </summary>
        internal static string CommandPointsRemoveSuccess {
            get {
                return ResourceManager.GetString("CommandPointsRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody&apos;s points were set to {0} by {1}..
        /// </summary>
        internal static string CommandPointsSetAllSuccess {
            get {
                return ResourceManager.GetString("CommandPointsSetAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandPointsSetNotFound {
            get {
                return ResourceManager.GetString("CommandPointsSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All online user&apos;s points were set to {0} by {1}..
        /// </summary>
        internal static string CommandPointsSetOnlineSuccess {
            get {
                return ResourceManager.GetString("CommandPointsSetOnlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s points were set to {1} by {2}..
        /// </summary>
        internal static string CommandPointsSetSuccess {
            get {
                return ResourceManager.GetString("CommandPointsSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results could be found. (@{1}).
        /// </summary>
        internal static string CommandPointsTopNoResults {
            get {
                return ResourceManager.GetString("CommandPointsTopNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who have the most points: {0}..
        /// </summary>
        internal static string CommandPointsTopSuccess {
            get {
                return ResourceManager.GetString("CommandPointsTopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to check the shout-out target. Please try again. (@{1}).
        /// </summary>
        internal static string CommandShoutoutError {
            get {
                return ResourceManager.GetString("CommandShoutoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Twitch username &quot;{0}&quot; is invalid. Please try again. (@{1}).
        /// </summary>
        internal static string CommandShoutoutNotFound {
            get {
                return ResourceManager.GetString("CommandShoutoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow {0} over at www.twitch.tv/{0}!.
        /// </summary>
        internal static string CommandShoutoutSuccess {
            get {
                return ResourceManager.GetString("CommandShoutoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;!time&quot; commands have been disabled. (@{0}).
        /// </summary>
        internal static string CommandTimeEnabledOffSuccess {
            get {
                return ResourceManager.GetString("CommandTimeEnabledOffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;!time&quot; commands have been enabled. (@{0}).
        /// </summary>
        internal static string CommandTimeEnabledOnSuccess {
            get {
                return ResourceManager.GetString("CommandTimeEnabledOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; doesn&apos;t exist. (@{1}).
        /// </summary>
        internal static string CommandTimeGetNotFound {
            get {
                return ResourceManager.GetString("CommandTimeGetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has watched the stream for {1}. (@{2}).
        /// </summary>
        internal static string CommandTimeGetSuccess {
            get {
                return ResourceManager.GetString("CommandTimeGetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You watched the stream for {0}. (@{1}).
        /// </summary>
        internal static string CommandTimeMainSuccess {
            get {
                return ResourceManager.GetString("CommandTimeMainSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t exist in the database yet. Please try again. (@{0}).
        /// </summary>
        internal static string CommandTimeMainWait {
            get {
                return ResourceManager.GetString("CommandTimeMainWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results could be found. (@{1}).
        /// </summary>
        internal static string CommandTimeTopNoResults {
            get {
                return ResourceManager.GetString("CommandTimeTopNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who watched the stream the longest: {0}..
        /// </summary>
        internal static string CommandTimeTopSuccess {
            get {
                return ResourceManager.GetString("CommandTimeTopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: &quot;{0}&quot;. (@{1}).
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Editor {
            get {
                object obj = ResourceManager.GetObject("Editor", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap GlobalMod {
            get {
                object obj = ResourceManager.GetObject("GlobalMod", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Moderator {
            get {
                object obj = ResourceManager.GetObject("Moderator", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Staff {
            get {
                object obj = ResourceManager.GetObject("Staff", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Viewer {
            get {
                object obj = ResourceManager.GetObject("Viewer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
