//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace th.AdminibotLegacy.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Adminibot")]
        public string OptionName {
            get {
                return ((string)(this["OptionName"]));
            }
            set {
                this["OptionName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OptionPassword {
            get {
                return ((string)(this["OptionPassword"]));
            }
            set {
                this["OptionPassword"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("TwitchPlaysPokemon")]
        public string OptionChannel {
            get {
                return ((string)(this["OptionChannel"]));
            }
            set {
                this["OptionChannel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Points")]
        public string OptionCurrency {
            get {
                return ((string)(this["OptionCurrency"]));
            }
            set {
                this["OptionCurrency"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public decimal OptionInterval {
            get {
                return ((decimal)(this["OptionInterval"]));
            }
            set {
                this["OptionInterval"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public decimal OptionPayout {
            get {
                return ((decimal)(this["OptionPayout"]));
            }
            set {
                this["OptionPayout"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OptionSubUrl {
            get {
                return ((string)(this["OptionSubUrl"]));
            }
            set {
                this["OptionSubUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public string InfoViewers {
            get {
                return ((string)(this["InfoViewers"]));
            }
            set {
                this["InfoViewers"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public string InfoPartnerStatus {
            get {
                return ((string)(this["InfoPartnerStatus"]));
            }
            set {
                this["InfoPartnerStatus"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public string InfoFollowers {
            get {
                return ((string)(this["InfoFollowers"]));
            }
            set {
                this["InfoFollowers"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string InfoChannelDisplayName {
            get {
                return ((string)(this["InfoChannelDisplayName"]));
            }
            set {
                this["InfoChannelDisplayName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string InfoBotDisplayName {
            get {
                return ((string)(this["InfoBotDisplayName"]));
            }
            set {
                this["InfoBotDisplayName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool OptionHideBotMsg {
            get {
                return ((bool)(this["OptionHideBotMsg"]));
            }
            set {
                this["OptionHideBotMsg"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool OptionHideStatusMsg {
            get {
                return ((bool)(this["OptionHideStatusMsg"]));
            }
            set {
                this["OptionHideStatusMsg"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool OptionComBtagEnabled {
            get {
                return ((bool)(this["OptionComBtagEnabled"]));
            }
            set {
                this["OptionComBtagEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("24")]
        public int OptionComBtagMaxChars {
            get {
                return ((int)(this["OptionComBtagMaxChars"]));
            }
            set {
                this["OptionComBtagMaxChars"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool OptionComTimeEnabled {
            get {
                return ((bool)(this["OptionComTimeEnabled"]));
            }
            set {
                this["OptionComTimeEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool OptionComPointsEnabled {
            get {
                return ((bool)(this["OptionComPointsEnabled"]));
            }
            set {
                this["OptionComPointsEnabled"] = value;
            }
        }
    }
}
