//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Media;

namespace th.AdminibotModern.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFA200FF")]
        public Color SelectedAccentColor {
            get {
                return ((Color)(this["SelectedAccentColor"]));
            }
            set {
                this["SelectedAccentColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("/FirstFloor.ModernUI;component/Assets/ModernUI.Dark.xaml")]
        public Uri SelectedThemeSource {
            get {
                return ((Uri)(this["SelectedThemeSource"]));
            }
            set {
                this["SelectedThemeSource"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Dark")]
        public string SelectedThemeDisplayName {
            get {
                return ((string)(this["SelectedThemeDisplayName"]));
            }
            set {
                this["SelectedThemeDisplayName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Large")]
        public string SelectedFontSize {
            get {
                return ((string)(this["SelectedFontSize"]));
            }
            set {
                this["SelectedFontSize"] = value;
            }
        }
    }
}
